// User-facing text, grouped by the component that shows it. Messages with values are functions.
// Import a group with an alias, e.g. `import { QUESTION_BANK_MESSAGES as MSG } from '../../constants';`

// Shared by several components
export const COMMON_MESSAGES = {
  addQuestionBank: 'Add to the question bank',
  failedLoadAssessments: 'Failed to load assessments',
  accessDeniedAdminRole: 'Access denied. Admin role required.',
};

export const AUTH_CONTEXT_MESSAGES = {
  useAuthOutsideProvider: 'useAuth must be used within AuthProvider',
};

export const THEME_CONTEXT_MESSAGES = {
  useThemeOutsideProvider: 'useTheme must be used within ThemeProvider',
};

export const LOGIN_PAGE_MESSAGES = {
  signContinuePlatform: 'Sign in to continue to the platform',
};

export const INVITE_PAGE_MESSAGES = {
  linkCouldNotOpened: 'This link could not be opened.',
  couldNotStartTest: 'Could not start the test. Please try again.',
  youveBeenInvitedCoding: 'You\'ve been invited to a coding assessment',
  youreCurrentlySigned: 'You\'re currently signed in as ',
  continuingSwitchDetailsBelow: '. Continuing will switch to the details below.',
  useSameEmailIf: 'Use the same email if you need to come back and continue.',
  goSign: 'Go to sign in',
  timerStartsOnlyWhen: 'The timer starts only when you click ',
  nextScreenDuringTest: ' on the next screen. During the test, leaving the tab 3 times submits it automatically.',
  ifThinkMistakeContact: 'If you think this is a mistake, contact the person who sent you the link.',
};

export const ADMIN_LAYOUT_MESSAGES = {
  codeNotReallyExecuted: 'Code is not really executed. Set JUDGE_MODE=live in server/.env to use Judge0.',
};

export const ASSESSMENT_DASHBOARD_MESSAGES = {
  candidatesOverallScoreAll: 'Candidates by overall score, all assessments',
  failedLoadDashboard: 'Failed to load dashboard',
  overviewAssessmentsCandidatePerformance: 'Overview of your assessments and candidate performance',
  notVisibleCandidates: 'Not visible to candidates',
  closedAdmin: 'Closed by an admin',
  endDateHasPassed: 'End date has passed',
  noCandidateActivityYet: 'No candidate activity yet.',
  createAssessmentStartInviting: 'Create an assessment to start inviting candidates.',
  randomSubsetPerCandidate: 'Random subset per candidate',
  closeStopAcceptingCandidates: 'Close: stop accepting candidates and mark as completed',
};

export const REVIEW_QUEUE_MESSAGES = {
  approvedAddedQuestionBank: 'Approved and added to the question bank.',
  rejectedNotUsed: 'Rejected. It will not be used.',
  failedLoadReviewQueue: 'Failed to load the review queue',
  aiGeneratedQuestionsStay: 'AI-generated questions stay here until someone approves them. Approving re-runs validation, and a question that fails any check can\'t be approved until it\'s fixed.',
  questionsGenerateAiSave: 'Questions you generate with AI and save for review will appear here.',
  fixFailedChecksFirst: 'Fix the failed checks first',
  notValidatedYetClick: 'Not validated yet. Click Validate.',
};

export const QUESTION_BANK_MESSAGES = {
  failedLoadQuestions: 'Failed to load questions',
  deleteUsedQuestionConfirm: (title: string, used: number) => `"${title}" is used in ${used} assessment${used === 1 ? '' : 's'}. Deleting it removes it from those assessments and deletes candidates' answers to it. Continue?`,
  deleteQuestionConfirm: (title: string) => `Delete "${title}"? This cannot be undone.`,
  failedDeleteQuestion: 'Failed to delete question',
  failedLoadQuestion: 'Failed to load question',
  pleaseSelectMarkdownMd: 'Please select a Markdown (.md) file',
  fileTooLargeMaximum: 'File is too large. Maximum size is 2MB.',
  failedImportMdFile: 'Failed to import MD file',
  questionsEasyMediumHard: (questionCount: number, easy: number, medium: number, hard: number) => `${questionCount} questions · ${easy} easy · ${medium} medium · ${hard} hard`,
  importMdFile: 'Import from MD file',
  searchQuestionsTitle: 'Search questions by title...',
  createFirstQuestionGet: 'Create your first question to get started.',
  noQuestionsMatchThese: 'No questions match these filters.',
  generatedAiApproved: 'Generated by AI and approved',
};

export const PROFILE_PAGE_MESSAGES = {
  nameEmailRequired: 'Name and email are required.',
  enterValidEmailAddress: 'Enter a valid email address.',
  manageAccountInformation: 'Manage your account information.',
};

export const QUESTION_FORM_MESSAGES = {
  titleProblemStatementRequired: 'Title and problem statement are required.',
  addLeast2Answer: 'Add at least 2 answer options.',
  twoOptionsHaveSame: 'Two options have the same text.',
  markLeastOneOption: 'Mark at least one option as correct.',
  failedSaveQuestionCheck: 'Failed to save question. Check the console for details.',
  candidateWritesProgramGraded: 'Candidate writes a program; graded by test cases',
  candidatePicksAnswerGraded: 'Candidate picks an answer; graded automatically',
  typeCantChangedAfter: 'The type can\'t be changed after a question is created.',
  twoSumReverseLinkedExample: 'e.g. Two Sum, Reverse Linked List',
  arraysReactHooksExample: 'e.g. Arrays, React hooks',
  cpuTimeLimitSeconds: 'CPU Time Limit (seconds)',
  problemStatementMarkdownSupported: 'Problem Statement (Markdown supported)',
  writeProblemStatementHere: 'Write the problem statement here. Markdown is supported.\n\n## Example:\nGiven an array of integers, find two numbers that add up to a specific target.\n\n**Input:** nums = [2, 7, 11, 15], target = 9\n**Output:** [0, 1]',
  tickEveryCorrectAnswer: 'Tick every correct answer. With more than one ticked, candidates are told to select all that apply, and they must pick exactly those to score.',
  unmarkOptionCorrect: (value: string) => `Unmark option ${value} as correct`,
  markOptionCorrect: (value: string) => `Mark option ${value} as correct`,
  shownAdminsReports: '(shown to admins in reports)',
  whyCorrectAnswerCorrect: 'Why the correct answer is correct',
  sampleTestCaseVisible: 'Sample test case (visible to candidate)',
  codePreFilledEditor: 'This code will be pre-filled in the editor when a candidate starts the question.',
};

export const SHARE_LINKS_MODAL_MESSAGES = {
  failedLoadLinks: 'Failed to load links',
  failedCreateLink: 'Failed to create link',
  failedTurnOffLink: 'Failed to turn off link',
  anyoneLinkTakeTest: 'Anyone with a link can take this test. They enter their name and email and start straight away. No account or password needed.',
  peopleOpenLinkBut: '. People can open the link, but they can\'t start until you publish it.',
  optionalOnlySee: '(optional, only you see it)',
  campusDriveNieExample: 'e.g. Campus drive — NIE',
  noLinksYetCreate: 'No links yet. Create one to share this test.',
};

export const ASSESSMENT_MANAGER_MESSAGES = {
  deleteTakenAssessmentConfirm: (name: string, taken: number) => `Delete "${name}"? ${taken} candidate result${taken === 1 ? '' : 's'} will be permanently deleted too.`,
  deleteAssessmentConfirm: (name: string) => `Delete "${name}"? This cannot be undone.`,
  createConfigurePublishCoding: 'Create, configure and publish coding assessments',
  createFirstAssessmentQuestion: 'Create your first assessment from the question bank.',
  noAssessmentsMatchFilter: 'No assessments match this filter.',
  createLinkAnyoneUse: 'Create a link anyone can use to take this test',
  makeVisibleCandidates: 'Make visible to candidates',
};

export const ASSESSMENT_FORM_MESSAGES = {
  giveAssessmentName: 'Give the assessment a name.',
  chooseLeastOneQuestion: 'Choose at least one question type.',
  addLeastOneQuestion: 'Add at least one question before publishing.',
  noQuestionsSelectedYet: 'No questions selected yet.',
  selectedQuestionTypeDidnt: (wrongTypeCount: number, value: string) => `${wrongTypeCount} selected question${wrongTypeCount === 1 ? ' is' : 's are'} a type you didn't choose (${value}).`,
  noTestCasesSo: (value: string, untestedCount: number) => `${value} ${untestedCount === 1 ? 'has' : 'have'} no test cases, so ${untestedCount === 1 ? 'it' : 'they'} can't be graded.`,
  marksMustWholeNumbers: 'Marks must be whole numbers between 1 and 1000.',
  someQuestionsArentAlthough: (difficulty: string) => `Some questions aren't "${difficulty}" although that's the target difficulty.`,
  durationMustBetween1: 'Duration must be between 1 and 600 minutes.',
  passingScoreMustBetween: 'Passing score must be between 0 and 100%.',
  questionsPerCandidateMust: (questionCount: number) => `Questions per candidate must be between 1 and the ${questionCount} selected.`,
  closingTimeMustAfter: 'The closing time must be after the opening time.',
  closingTimePastSo: 'The closing time is in the past, so candidates could not start.',
  addLeastOneAllowed: 'Add at least one allowed email or @domain, or choose another access option.',
  someAllowedEntriesNot: 'Some allowed entries are not valid emails or @domains.',
  attemptsMustBetween1: 'Attempts must be between 1 and 10.',
  failedSaveAssessment: 'Failed to save assessment',
  failedUpdateStatus: 'Failed to update status',
  basicDetailsQuestionsConfiguration: 'Basic details → questions → configuration → review → generate → publish',
  alreadyTakenAssessmentChanging: ' already taken this assessment. Changing questions or marks will change how their existing results are scored.',
  campusHiring2026RoundExample: 'e.g. Campus Hiring 2026 — Round 1',
  shownCandidatesTheirDashboard: 'Shown to candidates on their dashboard',
  shownStartScreenBefore: 'Shown on the start screen before the timer begins.',
  programsGradedTestCases: 'Programs graded by test cases',
  matchingQuestionsShownFirst: 'Matching questions are shown first in the next step.',
  questionBankEmpty: 'The question bank is empty.',
  noMatchingQuestionsChange: 'No matching questions. Change the filters, or generate new ones with AI.',
  addQuestionsBankDefault: 'Add questions from the bank. Default marks: easy 10, medium 20, hard 30. You can change them.',
  eachCandidateGetsRandom: (questionCount: number) => `Each candidate gets a random ${questionCount}.`,
  leaveEmptyEveryoneGet: 'Leave empty for everyone to get all questions.',
  latestAttemptCountsEarlier: 'The latest attempt counts; earlier scores are kept in the report.',
  oneAttemptPerCandidate: 'One attempt per candidate.',
  leaveEmptyAllowStarting: 'Leave empty to allow starting any time. Candidates already mid-test can always finish.',
  whoTake: ' Who can take it',
  everyoneAccountPlusAnyone: 'Everyone with an account, plus anyone you send a share link to.',
  onlySpecificEmailsDomains: 'Only specific emails or domains',
  candidatesMustMatchAllow: 'Candidates must match the allow-list below, including link joiners.',
  onlyPeopleShareLink: 'Only people with a share link',
  hiddenOtherCandidatesShare: 'Hidden from other candidates; share links are the only way in.',
  allowWholeOrganisation: ' to allow a whole organisation.',
  eachCandidateGetsDifferent: 'Each candidate gets a different (but stable) order.',
  multipleChoiceOptionsAppear: 'Multiple-choice options appear in a different order for each candidate.',
  showResultsCandidates: 'Show results to candidates',
  ifOffCandidatesOnly: 'If off, candidates only see a confirmation after submitting.',
  noneSelectedAllLanguages: 'None selected = all languages allowed.',
  savesAssessmentItsQuestions: 'This saves the assessment with its questions and settings',
  draftCandidatesCantSee: ' as a draft. Candidates can’t see it until you publish.',
  generateAssessmentFirst: 'Generate the assessment first.',
  visibleCandidatesOpens: (startAt: string) => `Visible to candidates; opens ${startAt}.`,
  candidatesStartNow: 'Candidates can start now.',
  haveUnsavedChangesPublishing: 'You have unsaved changes; publishing saves them first.',
  assessmentOnlyReachableThrough: 'This assessment is only reachable through share links.',
  createLinkAnyoneUse: 'Create a link anyone can use to take this test.',
};

export const AI_QUESTION_STUDIO_MESSAGES = {
  generateQuestionsAi: 'Generate questions with AI',
  describeWhatNeedReview: 'Describe what you need, review and edit the drafts, validate them, then approve them into the question bank',
  aiRunningBuiltStand: 'AI is running on the built-in stand-in until the AI backend is connected. Output is realistic sample content.',
  approvedAddedQuestionBank: ' approved and added to the question bank: ',
  savedReviewQueueApproval: ' saved to the review queue for approval later.',
  stayedReviewQueue: '" stayed in the review queue: ',
  goQuestionBank: 'Go to question bank',
  whatDoNeed: 'What do you need?',
  frontendEngineeringArraysExample: 'e.g. Frontend engineering, Arrays',
  typeSkillPressEnter: 'Type a skill and press Enter',
  focusRealWorldScenariosExample: 'e.g. focus on real-world scenarios, avoid trick questions',
  generatingAgainReplacesCurrent: 'Generating again replaces the current drafts.',
  draftsAppearHere: 'Drafts will appear here',
  nothingAddedQuestionBank: 'Nothing is added to the question bank until you approve it.',
  keepReviewQueueSomeone: 'Keep in the review queue for someone to approve later',
  fixDeselectFailingQuestions: 'Fix or deselect the failing questions',
  hiddenTestCasesReference: ' hidden test cases · reference solution ',
  editingClearsQuestionsValidation: ' Editing clears this question\'s validation. Validate again before approving.',
  optionsTickCorrectAnswer: 'Options — tick the correct answer(s)',
  usedVerifyExpectedOutputs: '— used to verify expected outputs',
};

export const INTERVIEW_LIST_MESSAGES = {
  planInterviewsAiRun: 'Plan interviews with AI, run them with live code and notes, and evaluate candidates by skill',
  failedLoadInterviews: 'Failed to load interviews',
  createInterviewGetAi: 'Create an interview to get an AI-suggested plan you can edit.',
};

export const INTERVIEW_PLANNER_MESSAGES = {
  describeRoleCandidateGet: 'Describe the role and the candidate, and get a time-boxed plan you can edit',
  whatRoleNeedsTechnologies: 'What the role needs: technologies, responsibilities, level',
  experienceExample: 'e.g. 4 years building React apps; led a design-system migration',
  reactJavascriptDsaPress: 'React, JavaScript, DSA… press Enter',
  couldNotCreatePlan: 'Could not create a plan',
  interviewPlanAppearHere: 'Your interview plan will appear here',
  addRequiredSkillsDuration: 'Add the required skills and duration, then generate. You can edit everything.',
  goalSection: 'Goal for this section',
  questionsBecomeInterviewChecklist: 'Questions become the interview checklist. You can add more during the interview.',
  couldNotCreateInterview: 'Could not create the interview',
  enterCandidateName: 'Enter the candidate name',
};

export const INTERVIEW_WORKSPACE_MESSAGES = {
  addQuestionBegin: 'Add a question to begin.',
  saveFailedKeepTyping: 'Save failed — keep typing to retry',
  captureCandidatesExplanationThey: 'Capture the candidate\'s explanation as they speak',
  hintsGivenFollowUps: 'Hints given, follow-ups, your impressions',
  runCodeSeeOutput: 'Run the code to see output.',
  captureAnswerCodeNotes: 'Capture an answer, code or notes, then generate. Every observation cites the evidence it\'s based on.',
  aiObservationsSupportJudgement: 'AI observations support your judgement; they are not a verdict. Skills in scope: ',
  evidenceRating: (skill: string) => `Evidence for your ${skill} rating`,
  keyStrengthsConcernsReason: 'Key strengths, concerns and the reason for your recommendation',
};

export const SUBMISSIONS_VIEWER_MESSAGES = {
  failedExportResults: 'Failed to export results',
  failedLoadSubmissions: 'Failed to load submissions.',
  downloadEveryCandidatesResult: 'Download every candidate\'s result as a spreadsheet',
  noCandidatesHaveTaken: 'No candidates have taken this assessment.',
  searchCandidateName: 'Search by candidate name...',
  noCandidatesMatchThese: 'No candidates match these filters.',
};

export const CANDIDATE_REPORT_MESSAGES = {
  noSubmissionsFoundCandidate: 'No submissions found for this candidate.',
  failedLoadReportData: 'Failed to load report data.',
  failedDownloadReportPlease: 'Failed to download report. Please try again.',
  noEmailFile: 'No email on file',
  clickQuestionDetails: 'Click a question for details',
  tabSwitchLimitReached: 'Tab-switch limit reached. The test was auto-submitted.',
  notAttemptedNoCode: 'Not attempted. No code was submitted.',
  testCasesPassed: (testcases_passed: number, testcases_total: number) => `${testcases_passed} of ${testcases_total} test cases passed`,
  showMoreFailedCase: (hiddenCount: number) => `Show ${hiddenCount} more failed case${hiddenCount === 1 ? '' : 's'}`,
  noTabSwitchesDetected: 'No tab switches detected',
  onlySizeEachPaste: 'Only the size of each paste is recorded, never its content. Pastes include text copied from within the editor itself.',
  otherCandidates: '% of the other candidates',
};

export const EXAM_DASHBOARD_MESSAGES = {
  underMinute: 'in under a minute',
  haveTestProgressTimer: 'You have a test in progress. Your timer is still running.',
  haveTestOpenRight: (count: number) => `You have ${count} test${count === 1 ? '' : 's'} open right now.`,
  youreAllCaughtUp: 'You’re all caught up. New tests will appear here when they open.',
  whenAdminOpensNew: 'When an admin opens a new assessment for you, it will show up here.',
  noCompletedTestsYet: 'No completed tests yet',
  resultsAppearHereAfter: 'Your results will appear here after you submit a test.',
  continueWhereLeftOff: 'Continue where you left off',
  couldNotStartAnother: 'Could not start another attempt',
  noAnswersWereSubmitted: 'No answers were submitted',
  resultsNotSharedOrganiser: 'Results not shared by the organiser',
  startAnotherAttemptLatest: 'Start another attempt; the latest attempt counts',
  scoreEachCompletedTest: 'Score in each completed test',
  completeTestSeeScores: 'Complete a test to see your scores here.',
  timerKeepsRunning: 'The timer keeps running',
  startsWhenClickStart: 'It starts when you click Start and continues even if you close the page.',
  stayTestTab: 'Stay on the test tab',
  leavingTabRecorded3rd: 'Leaving the tab is recorded. The 3rd time submits your test automatically.',
  pastingCodeIntoEditor: 'Pasting code into the editor is logged for the reviewer.',
  workSaved: 'Your work is saved',
  answersAutoSaveEvery: 'Answers auto-save every few seconds and when you switch questions.',
};

export const TAB_SWITCH_WARNING_MESSAGES = {
  leftTestWindow: 'You left the test window',
  wereAway: 'You were away for ',
  hasBeenRecordedShared: '. This has been recorded and shared with the reviewer.',
  ifLeaveTestWindow: 'If you leave the test window again, your test will be submitted automatically.',
  testSubmittedAutomaticallyAfter: (remaining: number) => `Your test will be submitted automatically after ${remaining} more switch${remaining === 1 ? '' : 'es'}.`,
  tabActivityMonitoredLeaving: (limit: number) => `Tab activity is monitored. Leaving this tab ${limit} times submits your test.`,
  haveLeftTestWindow: (count: number, limit: number) => `You have left the test window ${count} times. Reaching ${limit} submits your test.`,
};

export const ASSESSMENT_VIEW_MESSAGES = {
  codeExceededTimeLimit: 'Your code exceeded the time limit. Optimize your solution and try again.',
  fiveMinutesLeftWarning: '5 minutes left — make sure your answers are confirmed.',
  oneMinuteLeftWarning: '1 minute left — your test will be submitted automatically.',
  failedLoadAssessment: 'Failed to load assessment',
  failedStartAssessmentPlease: 'Failed to start assessment. Please try again.',
  executionStats: (executionTime: string, memoryMb: string | null) => `\n\n--- Execution Time: ${executionTime}s | Memory: ${memoryMb ? memoryMb + 'MB' : 'N/A'} ---`,
  failedExecuteCode: 'Failed to execute code',
  failedRunTestCases: 'Failed to run test cases',
  failedSubmitTestPlease: 'Failed to submit test. Please try again.',
  clickRunCodeSee: 'Click "Run code" to see output here',
  assessmentIsntAvailable: 'This assessment isn\'t available',
  backMyAssessments: ' Back to my assessments',
  timerStartsOnceClick: 'The timer starts once you click "Start Assessment" and cannot be paused.',
  stayTabLeavingSwitching: 'Stay on this tab. Leaving it (switching tabs, minimising, or opening another app) is recorded. You get',
  timesSubmitsTestAutomatically: ' times submits your test automatically. Pasting code into the editor is also recorded.',
  finalGradingRunsAgainst: 'Final grading runs against hidden test cases, not just the samples shown.',
  sureWantSubmitCannot: 'Are you sure you want to submit? You cannot make changes after submission.',
  leftTestWindow: 'You left the test window ',
  timesSavedAnswersWere: ' times. Your saved answers were submitted automatically, and the reviewer can see every tab switch.',
  assessmentHasBeenSubmitted: 'Your assessment has been submitted successfully.',
  responsesBeingEvaluated: '. Your responses are being evaluated.',
  enterCustomInputHere: 'Enter custom input here (stdin)...\n\nWhen you click \'Run code\' with this tab active and input provided, your code will run against this custom input instead of the sample test cases.',
  runCustomInput: 'Run with Custom Input',
  runningCodeAgainstAll: 'Running your code against all test cases. This may take a moment...',
  selectAllApply: 'Select all that apply',
};

export const SUBMISSION_RESULT_MESSAGES = {
  noAnswerWasSubmitted: 'No answer was submitted for this question.',
  resultsNotFoundYet: 'Results not found yet. If you just submitted, they may still be processing.',
  testHasBeenSubmitted: 'Your test has been submitted successfully.',
  answersHaveBeenSubmitted: '. Your answers have been submitted',
  scoresAssessmentSharedHiring: ' Scores for this assessment are shared by the hiring team, not shown here.',
  hiddenTestOutputsNot: ' Hidden test outputs are not shown',
};
