import React, { useEffect, useRef, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import ReactMarkdown from 'react-markdown';
import AdminLayout from '../../components/AdminLayout';
import {
  getAIStatus, generateAssessmentFromResume, createAIAssessment, apiError,
} from '../../services/api';
import type { AIStatus, AIGenerationPreview, AIGeneratedQuestion } from '../../services/api';
import {
  Sparkles, Upload, FileText, X, Trash2, ChevronDown, CheckCircle, AlertTriangle, ShieldAlert,
  Target, Wand2, KeyRound, User, Briefcase,
} from 'lucide-react';

const MAX_PDF_MB = 5;
const DEFAULT_MARKS: Record<string, number> = { easy: 10, medium: 20, hard: 30 };
const LEVEL_LABEL: Record<string, string> = { intern: 'Intern', junior: 'Junior', mid: 'Mid-level', senior: 'Senior', staff: 'Staff / Principal' };

// Messages rotated while Claude works, so a multi-minute wait doesn't look frozen
const PROGRESS_STEPS = [
  'Reading the resume...',
  'Identifying skills and experience level...',
  'Designing problems around the candidate’s background...',
  'Writing statements and test cases...',
  'Checking expected outputs against a reference solution...',
];

type Stage = 'input' | 'generating' | 'review';

export default function AIAssessmentBuilder() {
  const navigate = useNavigate();
  const [status, setStatus] = useState<AIStatus | null>(null);
  const [stage, setStage] = useState<Stage>('input');
  const [error, setError] = useState('');

  // Input
  const [mode, setMode] = useState<'pdf' | 'text'>('pdf');
  const [file, setFile] = useState<File | null>(null);
  const [resumeText, setResumeText] = useState('');
  const [questionCount, setQuestionCount] = useState(3);
  const [focus, setFocus] = useState('');
  const [dragging, setDragging] = useState(false);
  const fileInput = useRef<HTMLInputElement>(null);

  // Progress
  const [step, setStep] = useState(0);
  const [elapsed, setElapsed] = useState(0);

  // Review
  const [preview, setPreview] = useState<AIGenerationPreview | null>(null);
  const [questions, setQuestions] = useState<AIGeneratedQuestion[]>([]);
  const [name, setName] = useState('');
  const [timeLimit, setTimeLimit] = useState(60);
  const [passingScore, setPassingScore] = useState(60);
  const [creating, setCreating] = useState(false);

  useEffect(() => {
    getAIStatus().then(setStatus).catch((err) => setError(apiError(err, 'Could not check AI availability')));
  }, []);

  useEffect(() => {
    if (stage !== 'generating') return;
    setStep(0);
    setElapsed(0);
    const tick = setInterval(() => setElapsed((s) => s + 1), 1000);
    const rotate = setInterval(() => setStep((s) => Math.min(s + 1, PROGRESS_STEPS.length - 1)), 20000);
    return () => { clearInterval(tick); clearInterval(rotate); };
  }, [stage]);

  function pickFile(f: File | undefined | null) {
    setError('');
    if (!f) return;
    if (f.type !== 'application/pdf' && !f.name.toLowerCase().endsWith('.pdf')) {
      setError('Please upload a PDF file. For Word documents, paste the text instead.');
      return;
    }
    if (f.size > MAX_PDF_MB * 1024 * 1024) {
      setError(`The PDF must be ${MAX_PDF_MB} MB or smaller.`);
      return;
    }
    setFile(f);
  }

  const canGenerate = !!status?.configured && (mode === 'pdf' ? !!file : resumeText.trim().length >= 50);

  async function handleGenerate() {
    if (!canGenerate) return;
    setError('');
    setStage('generating');
    try {
      const input = mode === 'pdf'
        ? { resumePdfBase64: await fileToBase64(file!), questionCount, focus: focus.trim() || undefined }
        : { resumeText, questionCount, focus: focus.trim() || undefined };
      const result = await generateAssessmentFromResume(input);
      setPreview(result);
      setQuestions(result.questions);
      setName(`${result.candidate.name} — Tailored Assessment`);
      setTimeLimit(result.suggested_time_minutes);
      setStage('review');
    } catch (err) {
      setError(apiError(err, 'Failed to generate questions'));
      setStage('input');
    }
  }

  async function handleCreate() {
    if (!questions.length || !name.trim()) return;
    setCreating(true);
    setError('');
    try {
      const created = await createAIAssessment({
        name: name.trim(),
        description: preview ? `Generated by AI from ${preview.candidate.name}'s resume.` : undefined,
        timeLimitMinutes: timeLimit,
        passingScore,
        questions: questions.map(({ verification: _v, rationale: _r, reference_solution_python: _s, ...q }) => q),
      });
      navigate(`/admin/assessments/${created.id}/edit`);
    } catch (err) {
      setError(apiError(err, 'Failed to create assessment'));
      setCreating(false);
    }
  }

  function startOver() {
    setStage('input');
    setPreview(null);
    setQuestions([]);
    setError('');
  }

  const totalMarks = questions.reduce((sum, q) => sum + (DEFAULT_MARKS[q.difficulty] ?? 10), 0);
  const hasUnverified = questions.some((q) => q.verification.status !== 'verified');

  return (
    <AdminLayout
      title="Generate assessment with AI"
      subtitle="Upload a candidate's resume and get coding questions written for their skills and experience"
      maxWidth="max-w-5xl"
    >
      {error && (
        <div className="mb-5 p-3 rounded-lg bg-red-500/10 border border-red-500/25 text-sm text-red-700 flex items-start gap-2">
          <AlertTriangle className="w-4 h-4 shrink-0 mt-0.5" /> <span>{error}</span>
        </div>
      )}

      {status && !status.configured && (
        <div className="mb-5 card border-amber-500/30 bg-amber-500/[0.06] flex items-start gap-3">
          <KeyRound className="w-5 h-5 text-amber-600 shrink-0 mt-0.5" />
          <div className="text-sm">
            <p className="font-semibold text-white">AI is not set up yet</p>
            <p className="text-surface-400 mt-1">
              Add <code className="px-1 py-0.5 rounded bg-surface-800 text-surface-200">ANTHROPIC_API_KEY=your-key</code> to{' '}
              <code className="px-1 py-0.5 rounded bg-surface-800 text-surface-200">server/.env</code>, then restart the server.
            </p>
          </div>
        </div>
      )}

      {/* ═══ STEP 1: INPUT ═══ */}
      {stage === 'input' && (
        <div className="grid lg:grid-cols-3 gap-6">
          <div className="card lg:col-span-2">
            <div className="flex items-center justify-between mb-4">
              <h2 className="text-sm font-semibold text-white">1. Candidate resume</h2>
              <div className="flex rounded-lg bg-surface-800 p-0.5 text-xs font-medium">
                {(['pdf', 'text'] as const).map((m) => (
                  <button
                    key={m}
                    type="button"
                    onClick={() => { setMode(m); setError(''); }}
                    className={`px-3 py-1.5 rounded-md transition-colors cursor-pointer ${mode === m ? 'bg-surface-900 text-white shadow-sm' : 'text-surface-500 hover:text-surface-300'}`}
                  >
                    {m === 'pdf' ? 'Upload PDF' : 'Paste text'}
                  </button>
                ))}
              </div>
            </div>

            {mode === 'pdf' ? (
              file ? (
                <div className="flex items-center justify-between gap-3 p-4 rounded-xl border border-surface-700 bg-surface-950">
                  <div className="flex items-center gap-3 min-w-0">
                    <div className="w-10 h-10 rounded-lg bg-red-500/10 text-red-600 flex items-center justify-center shrink-0">
                      <FileText className="w-5 h-5" />
                    </div>
                    <div className="min-w-0">
                      <p className="text-sm font-medium text-white truncate">{file.name}</p>
                      <p className="text-xs text-surface-500">{(file.size / 1024).toFixed(0)} KB</p>
                    </div>
                  </div>
                  <button type="button" onClick={() => setFile(null)} className="btn-ghost p-2" aria-label="Remove file">
                    <X className="w-4 h-4" />
                  </button>
                </div>
              ) : (
                <button
                  type="button"
                  onClick={() => fileInput.current?.click()}
                  onDragOver={(e) => { e.preventDefault(); setDragging(true); }}
                  onDragLeave={() => setDragging(false)}
                  onDrop={(e) => { e.preventDefault(); setDragging(false); pickFile(e.dataTransfer.files[0]); }}
                  className={`w-full flex flex-col items-center justify-center gap-2 py-12 rounded-xl border-2 border-dashed transition-colors cursor-pointer ${dragging ? 'border-primary-500 bg-primary-500/5' : 'border-surface-700 hover:border-primary-500/50 hover:bg-surface-950'}`}
                >
                  <div className="w-12 h-12 rounded-xl bg-primary-500/10 text-primary-600 flex items-center justify-center">
                    <Upload className="w-6 h-6" />
                  </div>
                  <p className="text-sm font-medium text-white">Drop a resume PDF here, or click to browse</p>
                  <p className="text-xs text-surface-500">PDF up to {MAX_PDF_MB} MB</p>
                </button>
              )
            ) : (
              <div>
                <textarea
                  value={resumeText}
                  onChange={(e) => setResumeText(e.target.value)}
                  rows={12}
                  placeholder="Paste the candidate's resume here..."
                  className="input font-mono text-xs leading-relaxed resize-y"
                />
                <p className="text-xs text-surface-500 mt-1.5">{resumeText.trim().length < 50 ? 'Paste at least a few lines of the resume.' : `${resumeText.length.toLocaleString()} characters`}</p>
              </div>
            )}
            <input ref={fileInput} type="file" accept="application/pdf,.pdf" className="hidden" onChange={(e) => { pickFile(e.target.files?.[0]); e.target.value = ''; }} />
            <p className="text-xs text-surface-500 mt-4">
              The resume is sent to Anthropic&apos;s Claude API to write the questions. It is not saved by this platform.
            </p>
          </div>

          <div className="card flex flex-col">
            <h2 className="text-sm font-semibold text-white mb-4">2. Options</h2>
            <label className="label" htmlFor="qcount">Number of questions</label>
            <div className="flex gap-2 mb-5" id="qcount">
              {Array.from({ length: (status?.maxQuestions ?? 5) - (status?.minQuestions ?? 2) + 1 }, (_, i) => (status?.minQuestions ?? 2) + i).map((n) => (
                <button
                  key={n}
                  type="button"
                  onClick={() => setQuestionCount(n)}
                  className={`flex-1 py-2 rounded-lg text-sm font-semibold border transition-colors cursor-pointer ${questionCount === n ? 'border-primary-500 bg-primary-500/10 text-primary-700' : 'border-surface-700 text-surface-400 hover:border-surface-500'}`}
                >
                  {n}
                </button>
              ))}
            </div>
            <label className="label" htmlFor="focus">Role or focus <span className="text-surface-500 font-normal">(optional)</span></label>
            <input
              id="focus"
              value={focus}
              onChange={(e) => setFocus(e.target.value.slice(0, 200))}
              placeholder="e.g. Backend engineer, data pipelines"
              className="input mb-5"
            />
            <div className="mt-auto">
              <button type="button" onClick={handleGenerate} disabled={!canGenerate} className="btn-primary w-full py-2.5">
                <Wand2 className="w-4 h-4" /> Generate questions
              </button>
              <p className="text-xs text-surface-500 mt-2 text-center">Usually takes 1–3 minutes</p>
            </div>
          </div>
        </div>
      )}

      {/* ═══ STEP 2: GENERATING ═══ */}
      {stage === 'generating' && (
        <div className="card max-w-xl mx-auto text-center py-12">
          <div className="relative w-16 h-16 mx-auto mb-5">
            <div className="absolute inset-0 rounded-full border-4 border-primary-500/20" />
            <div className="absolute inset-0 rounded-full border-4 border-primary-600 border-t-transparent animate-spin" />
            <Sparkles className="absolute inset-0 m-auto w-6 h-6 text-primary-600" />
          </div>
          <h2 className="text-lg font-semibold text-white">Writing tailored questions</h2>
          <p className="text-sm text-surface-400 mt-2 min-h-[1.25rem]" aria-live="polite">{PROGRESS_STEPS[step]}</p>
          <p className="text-xs text-surface-500 mt-4 tabular-nums">
            {Math.floor(elapsed / 60)}:{String(elapsed % 60).padStart(2, '0')} elapsed · keep this page open
          </p>
        </div>
      )}

      {/* ═══ STEP 3: REVIEW ═══ */}
      {stage === 'review' && preview && (
        <div className="space-y-6">
          <CandidateCard candidate={preview.candidate} />

          <div className="flex items-baseline justify-between">
            <h2 className="text-lg font-semibold text-white">Generated questions</h2>
            <span className="text-xs text-surface-500">{questions.length} question{questions.length === 1 ? '' : 's'} · {totalMarks} marks</span>
          </div>

          {hasUnverified && (
            <div className="p-3 rounded-lg bg-amber-500/10 border border-amber-500/25 text-sm text-amber-800 flex items-start gap-2">
              <ShieldAlert className="w-4 h-4 shrink-0 mt-0.5" />
              <span>
                Some test cases could not be verified automatically{status?.canVerify ? '' : ' (the mock judge is on)'}.
                Check the expected outputs before publishing. You can edit questions after creating the assessment.
              </span>
            </div>
          )}

          <div className="space-y-4">
            {questions.map((q, i) => (
              <QuestionPreview
                key={`${i}-${q.title}`}
                q={q}
                index={i}
                onRemove={questions.length > 1 ? () => setQuestions((qs) => qs.filter((_, j) => j !== i)) : undefined}
              />
            ))}
          </div>

          {/* Settings + create */}
          <div className="card">
            <h2 className="text-sm font-semibold text-white mb-4">Assessment settings</h2>
            <div className="grid sm:grid-cols-4 gap-4">
              <div className="sm:col-span-2">
                <label className="label" htmlFor="aname">Name</label>
                <input id="aname" value={name} onChange={(e) => setName(e.target.value)} className="input" maxLength={200} />
              </div>
              <div>
                <label className="label" htmlFor="atime">Time limit (minutes)</label>
                <input id="atime" type="number" min={5} max={600} value={timeLimit} onChange={(e) => setTimeLimit(Math.max(5, Math.min(600, Number(e.target.value) || 5)))} className="input" />
              </div>
              <div>
                <label className="label" htmlFor="apass">Passing score (%)</label>
                <input id="apass" type="number" min={0} max={100} value={passingScore} onChange={(e) => setPassingScore(Math.max(0, Math.min(100, Number(e.target.value) || 0)))} className="input" />
              </div>
            </div>
            <div className="flex flex-wrap items-center justify-between gap-3 mt-6 pt-5 border-t border-surface-800">
              <p className="text-xs text-surface-500 max-w-md">
                The assessment is saved as a <span className="font-semibold text-surface-300">draft</span>. Candidates can&apos;t see it until you publish it.
              </p>
              <div className="flex gap-2">
                <button type="button" onClick={startOver} className="btn-outline" disabled={creating}>Start over</button>
                <button type="button" onClick={handleCreate} className="btn-primary" disabled={creating || !questions.length || !name.trim()}>
                  <CheckCircle className="w-4 h-4" /> {creating ? 'Creating...' : 'Create draft assessment'}
                </button>
              </div>
            </div>
          </div>
        </div>
      )}
    </AdminLayout>
  );
}

function fileToBase64(file: File): Promise<string> {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onload = () => resolve(String(reader.result).split(',')[1] ?? '');
    reader.onerror = () => reject(new Error('Could not read the file'));
    reader.readAsDataURL(file);
  });
}

function CandidateCard({ candidate }: { candidate: AIGenerationPreview['candidate'] }) {
  return (
    <div className="card">
      <div className="flex flex-wrap items-start gap-4">
        <div className="w-12 h-12 rounded-xl bg-primary-500/10 text-primary-700 flex items-center justify-center shrink-0">
          <User className="w-6 h-6" />
        </div>
        <div className="flex-1 min-w-0">
          <p className="text-[11px] font-semibold text-primary-600 uppercase tracking-wider flex items-center gap-1">
            <Sparkles className="w-3 h-3" /> Candidate profile (from resume)
          </p>
          <h2 className="text-xl font-bold text-white mt-0.5">{candidate.name}</h2>
          <div className="flex flex-wrap items-center gap-x-4 gap-y-1 mt-1 text-sm text-surface-400">
            <span className="flex items-center gap-1.5"><Briefcase className="w-3.5 h-3.5" /> {LEVEL_LABEL[candidate.experience_level] ?? candidate.experience_level}</span>
            <span>{candidate.years_of_experience} yr{candidate.years_of_experience === 1 ? '' : 's'} experience</span>
            {candidate.primary_languages.length > 0 && <span>{candidate.primary_languages.join(', ')}</span>}
          </div>
          <p className="text-sm text-surface-300 mt-3 leading-relaxed">{candidate.summary}</p>
          {candidate.skills.length > 0 && (
            <div className="flex flex-wrap gap-1.5 mt-3">
              {candidate.skills.slice(0, 16).map((s) => (
                <span key={s} className="badge bg-surface-800 text-surface-300 ring-1 ring-surface-700">{s}</span>
              ))}
            </div>
          )}
        </div>
      </div>
    </div>
  );
}

function VerificationBadge({ v }: { v: AIGeneratedQuestion['verification'] }) {
  if (v.status === 'verified') {
    return (
      <span className="badge bg-emerald-500/10 text-emerald-700 ring-1 ring-emerald-500/25 gap-1" title={v.dropped ? `${v.dropped} incorrect test case(s) were removed` : 'All test cases match the reference solution'}>
        <CheckCircle className="w-3 h-3" /> Verified{v.dropped ? ` · ${v.dropped} removed` : ''}
      </span>
    );
  }
  if (v.status === 'failed') {
    return <span className="badge bg-red-500/10 text-red-700 ring-1 ring-red-500/25 gap-1" title={v.reason}><AlertTriangle className="w-3 h-3" /> Needs review</span>;
  }
  return <span className="badge bg-amber-500/10 text-amber-700 ring-1 ring-amber-500/25 gap-1" title={v.reason}><ShieldAlert className="w-3 h-3" /> Unverified</span>;
}

function QuestionPreview({ q, index, onRemove }: { q: AIGeneratedQuestion; index: number; onRemove?: () => void }) {
  const [open, setOpen] = useState(index === 0);
  const samples = q.test_cases.filter((t) => t.is_sample);
  const hidden = q.test_cases.length - samples.length;
  const diffClass = q.difficulty === 'easy' ? 'badge-easy' : q.difficulty === 'medium' ? 'badge-medium' : 'badge-hard';

  return (
    <div className="card p-0 overflow-hidden">
      <div className="flex items-start justify-between gap-4 p-5">
        <div className="flex items-start gap-3 min-w-0">
          <span className="w-8 h-8 rounded-lg bg-primary-500/10 text-primary-700 flex items-center justify-center text-sm font-semibold shrink-0">Q{index + 1}</span>
          <div className="min-w-0">
            <h3 className="font-semibold text-white">{q.title}</h3>
            <div className="flex flex-wrap items-center gap-1.5 mt-1.5">
              <span className={`${diffClass} capitalize`}>{q.difficulty}</span>
              {q.tags.map((t) => <span key={t} className="badge bg-surface-800 text-surface-400 ring-1 ring-surface-700">{t}</span>)}
              <VerificationBadge v={q.verification} />
            </div>
          </div>
        </div>
        <div className="flex items-center gap-2 shrink-0">
          <span className="text-xs text-surface-500 tabular-nums hidden sm:inline">{DEFAULT_MARKS[q.difficulty]} marks</span>
          {onRemove && (
            <button type="button" onClick={onRemove} className="btn-ghost p-2 hover:text-red-600" title="Remove this question" aria-label={`Remove ${q.title}`}>
              <Trash2 className="w-4 h-4" />
            </button>
          )}
        </div>
      </div>

      <div className="mx-5 mb-4 p-3 rounded-lg bg-primary-500/[0.05] border border-primary-500/15 text-sm text-surface-300 flex gap-2">
        <Target className="w-4 h-4 text-primary-600 shrink-0 mt-0.5" />
        <span><span className="font-medium text-primary-700">Why this question: </span>{q.rationale}</span>
      </div>

      <button
        type="button"
        onClick={() => setOpen((v) => !v)}
        className="w-full flex items-center justify-between px-5 py-2.5 border-t border-surface-800 bg-surface-950 hover:bg-surface-800/50 text-xs font-medium text-surface-400 cursor-pointer"
        aria-expanded={open}
      >
        <span className="flex items-center gap-3">
          <span>Problem statement &amp; test cases</span>
          <span className="text-surface-500 font-normal">{samples.length} sample · {hidden} hidden</span>
        </span>
        <ChevronDown className={`w-4 h-4 transition-transform ${open ? 'rotate-180' : ''}`} />
      </button>

      {open && (
        <div className="border-t border-surface-800 p-5 space-y-5">
          <div className="text-sm text-surface-300 leading-relaxed space-y-2 [&_strong]:text-white [&_ul]:list-disc [&_ul]:pl-5 [&_code]:px-1 [&_code]:rounded [&_code]:bg-surface-800 [&_code]:text-surface-100 [&_pre]:bg-surface-950 [&_pre]:p-3 [&_pre]:rounded-lg [&_pre]:overflow-x-auto">
            <ReactMarkdown>{q.statement}</ReactMarkdown>
          </div>
          <div>
            <p className="text-[11px] font-semibold text-surface-500 uppercase tracking-wider mb-2">Test cases</p>
            <div className="rounded-lg border border-surface-800 overflow-hidden">
              <table className="w-full text-xs">
                <thead>
                  <tr className="text-[10px] text-surface-500 uppercase tracking-wider bg-surface-950 border-b border-surface-800">
                    <th className="text-left font-medium px-3 py-2 w-20">Type</th>
                    <th className="text-left font-medium px-3 py-2">Input</th>
                    <th className="text-left font-medium px-3 py-2">Expected output</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-surface-800">
                  {q.test_cases.map((t, i) => (
                    <tr key={i} className="align-top">
                      <td className="px-3 py-2">
                        <span className={`badge ring-1 ${t.is_sample ? 'bg-sky-500/10 text-sky-700 ring-sky-500/25' : 'bg-surface-800 text-surface-500 ring-surface-700'}`}>{t.is_sample ? 'Sample' : 'Hidden'}</span>
                      </td>
                      <td className="px-3 py-2"><pre className="font-mono text-surface-100 whitespace-pre-wrap break-all max-h-32 overflow-y-auto [font-variant-ligatures:none]">{t.input}</pre></td>
                      <td className="px-3 py-2"><pre className="font-mono text-emerald-700 whitespace-pre-wrap break-all max-h-32 overflow-y-auto [font-variant-ligatures:none]">{t.expected_output}</pre></td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
